# version: "3.8"
# services:
#  vite_docker:
#    image: node:alpine
#    container_name: vite_docker
#    entrypoint: /bin/sh
#    ports:
#      - 3000:3000
#    working_dir: /src/app
#    volumes:
#      - type: bind
#        source: ./
#        target: /src/app
#    tty: true

version: "3.8"
services:
  vite_docker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vite_docker
    ports:
      - 5173:5173
    volumes:
      - ./:/app
    tty: true